baseurl = "http://www.gingerbill.org"
title = "gingerBill"
languageCode = "en-gb"
disqusShortname = "gingerBill"
copyright = "Copyright (c) 2007 - 2015, Ginger Bill; all rights reserved."
MetaDataFormat = "toml"
canonifyurls = true

[taxonomies]
	topic = "topics"
	tag = "tags"

[author]
	name = "Ginger Bill"
